---
- name: Print event payload ( for EE as code / testing )
  hosts: all
  sources:
  - template:
      delay: 5

  rules:
    - name: Print the payload you receive an event
      condition: event.title is defined
      actions:
        - debug:
            msg: "{{ event }}"
