---
- name: Watching for Problems on Dynatrace
  hosts: all
  sources:
    - template:
        delay: 5

  rules:
    - name: Print the payload you receive an event
      condition: event.payload.event_name == "push"
      actions:
        - debug:
            msg: "{{ event }}"
