---
- name: Demo of a rulebook using an event stream
  hosts: all
  sources:
    - template:
        delay: 5

  rules:
    - name: Print the payload you receive an event
      condition: event.payload is defined
      actions:
        - debug:
            msg: ">>>>>>>>>>>>>>>>  {{ event }}"
