---
- name: Demo of a rulebook using an event stream and exit once condition is met
  hosts: all
  sources:
    - template:
        delay: 5

  vars:
    event_received: false  # Track event status

  rules:
    - name: Print the payload and exit after receiving the first event
      condition: event.payload is defined and vars.event_received == false
      actions:
        - debug:
            msg: ">>>>>>>>>>>>>>>>  {{ event }}"
        - set_fact:
            event_received: true  # Mark the event as processed
        - shutdown:
            delay: 0.125  # Short delay before shutdown
            message: "Shutting down after processing the first event"

