---
- name: Demo of a rulebook using an event stream and exit once condition is met
  hosts: all
  sources:
    - template:
        delay: 5

  rules:
    - name: Print the payload and exit after first event
      condition: event.payload is defined
      actions:
        - debug:
            msg: ">>>>>>>>>>>>>>>>  {{ event }}"
        - shutdown:
            delay: 0.125
            message: "Shutting down after processing the event"

