name: Ansible Lint

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Ansible Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Update to the latest version

      - name: Set up Python
        uses: actions/setup-python@v5  # Update to the latest version
        with:
          python-version: '3.x'

      - name: Install ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint rulebooks/

